### ISSUE TITLE
Blocked host: example.com

### ISSUE THREAD

**Issue by ermiahp** [blindsidenetworks/scalelite#142]
Hi, I install all services and all are up and I don't know what to do next? I have bbb serves enabled but when I check example.com/bigbluebutton I get this page bellow 

Blocked host: example.com
To allow requests to example.com, add the following to your environment configuration:
config.hosts << "example.com"

**Comment by mohamedelashhab** [comment]
i have the same probleme 
have you fixed it ?

**Comment by premryp** [comment]
Hello I am facing the same issue. Any one fixed this issue ?

Blocked host: example.com
To allow requests to example.com, add the following to your environment configuration:
config.hosts << "example.com"

**Comment by matiasilva** [comment]
Hi guys. If you're looking for help, it might be better handled here: https://groups.google.com/forum/#!forum/bigbluebutton-setup.

**Comment by premryp** [comment]
@matiasilva really appreciate on your help. I cant able to view those pages. can you please pass me the instruction to fix the 
issue.

**Comment by matiasilva** [comment]
Hi @premryp. The above link was to a forum where people can give you support. Unfortunately, without knowing more about your setup I can't really give you any help.

**Comment by mohamedelashhab** [comment]
I fixed this probleme by remove http://bbbm.example.com from URL_HOST
in /etc/default/scalelite file

**Comment by premryp** [comment]
I followed the instruction from https://medium.com/@jesusfederico_39370/scalelite-lazy-deployment-745a7be849f6 there it mentioned .env file 
URL_HOST= domain .com

**Comment by premryp** [comment]
Any one here to help me.

**Comment by mohgh** [comment]
Has anyone fixed this issue?
I still have this problem and I'm sure it's not related to scalelite because it will happen even if I call the BBB server directly.
Also, this issue happens randomly.
